=== esther44/.net/exos/tpXmlPersonnes/personnes.dtd
<!ELEMENT personnes (personne*)>
<!ELEMENT personne (nom, prenom+, age, telephone+, mail?, adresse, comptes)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT age (#PCDATA)>

<!ELEMENT telephone (#PCDATA)>
<!ATTLIST telephone type (fix|portable) #REQUIRED>


<!ELEMENT mail (#PCDATA)>

<!ELEMENT adresse (numero, rue, cp)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT rue (#PCDATA)>
<!ELEMENT cp (#PCDATA)>


<!ELEMENT comptes (compte+)>
<!ELEMENT compte (rib)>
<!ATTLIST compte id ID #REQUIRED>
<!ATTLIST compte type (pro|perso) #REQUIRED>
<!ATTLIST compte banque (SG | BNP | CA) #REQUIRED>

<!ELEMENT rib (#PCDATA)>

=== esther44/.net/exos/tpXmlPersonnes/personnes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE personnes SYSTEM "personnes.dtd">

<personnes>
    <personne>
        <nom>Durand</nom>
        <prenom>Jean</prenom>
        <prenom>Luc</prenom>
        <age>35</age>
        <telephone type="fix">0147852369</telephone>
        <telephone type="portable">0623456789</telephone>
        <mail>jean.durand@example.com</mail>
        <adresse>
            <numero>12</numero>
            <rue>Rue des Lilas</rue>
            <cp>75010</cp>
        </adresse>
        <comptes>
            <compte id="c1" type="perso" banque="SG">
                <rib>FR7630004000031234567890143</rib>
            </compte>
            <compte id="c2" type="pro" banque="CA">
                <rib>FR7630004000039876543210123</rib>
            </compte>
        </comptes>
    </personne>

    <personne>
        <nom>Lemoine</nom>
        <prenom>Sophie</prenom>
        <age>28</age>
        <telephone type="portable">0678991122</telephone>
        <adresse>
            <numero>5</numero>
            <rue>Av. de la RÃ©publique</rue>
            <cp>33000</cp>
        </adresse>
        <comptes>
            <compte id="c3" type="perso" banque="BNP">
                <rib>FR7612345678901234567890123</rib>
            </compte>
        </comptes>
    </personne>
</personnes>
